USE vs_martinez
GO 

ALTER TABLE sys_logs ADD registro_grupo dm_char_corto
GO 

/****** Object:  Index [IX_SYS_TIMESTAMP]    Script Date: 01/30/2012 18:12:58 ******/
CREATE NONCLUSTERED INDEX [IX_SYS_TIMESTAMP] ON [dbo].[sys_logs] 
(
	[sys_timestamp] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

/****** Object:  Index [IX_REGISTRO_GRUPO]    Script Date: 01/30/2012 18:13:18 ******/
CREATE NONCLUSTERED INDEX [IX_REGISTRO_GRUPO] ON [dbo].[sys_logs] 
(
	[registro_grupo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_ALIAS_TABLA] ON [dbo].[sys_logs] 
(
	[alias_tabla] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


